/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as CreateRouteImport } from "./app/create";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as IndexRouteImport } from "./app/index";
import { Route as WcRouteImport } from "./app/wc";

const WcRoute = WcRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/wc",
  path: "/wc",
} as any);
const CreateRoute = CreateRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/create",
  path: "/create",
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/dashboard",
  path: "/dashboard",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRoute;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRoute;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRoute;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/create" | "/wc";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/create" | "/wc";
  id: "__root__" | "/" | "/dashboard" | "/create" | "/wc";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRoute;
  CreateRoute: typeof CreateRoute;
  WcRoute: typeof WcRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wc": {
      id: "/wc";
      path: "/wc";
      fullPath: "/wc";
      preLoaderRoute: typeof WcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create": {
      id: "/create";
      path: "/create";
      fullPath: "/create";
      preLoaderRoute: typeof CreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateRoute: CreateRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  IndexRoute: IndexRoute,
  WcRoute: WcRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
