/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as CreateRouteImport } from "./app/create";
import { Route as DashboardGoalsCreateRouteImport } from "./app/dashboard/goals/create";
import { Route as DashboardGoalsIndexRouteImport } from "./app/dashboard/goals/index";
import { Route as DashboardIndexRouteImport } from "./app/dashboard/index";
import { Route as DashboardRouteRouteImport } from "./app/dashboard/route";
import { Route as DashboardSavingsRouteImport } from "./app/dashboard/savings";
import { Route as DashboardSendIndexRouteImport } from "./app/dashboard/send/index";
import { Route as DashboardSettingsRouteImport } from "./app/dashboard/settings";
import { Route as DashboardWcRouteImport } from "./app/dashboard/wc";
import { Route as IndexRouteImport } from "./app/index";
import { Route as WcRouteImport } from "./app/wc";

const WcRoute = WcRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/wc",
  path: "/wc",
} as any);
const CreateRoute = CreateRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/create",
  path: "/create",
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/dashboard",
  path: "/dashboard",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/",
  path: "/",
} as any);
const DashboardWcRoute = DashboardWcRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/wc",
  path: "/wc",
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/settings",
  path: "/settings",
} as any);
const DashboardSavingsRoute = DashboardSavingsRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/savings",
  path: "/savings",
} as any);
const DashboardSendIndexRoute = DashboardSendIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/send/",
  path: "/send/",
} as any);
const DashboardGoalsIndexRoute = DashboardGoalsIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/goals/",
  path: "/goals/",
} as any);
const DashboardGoalsCreateRoute = DashboardGoalsCreateRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: "/goals/create",
  path: "/goals/create",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
  "/dashboard/savings": typeof DashboardSavingsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wc": typeof DashboardWcRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/goals/create": typeof DashboardGoalsCreateRoute;
  "/dashboard/goals": typeof DashboardGoalsIndexRoute;
  "/dashboard/send": typeof DashboardSendIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
  "/dashboard/savings": typeof DashboardSavingsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wc": typeof DashboardWcRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/goals/create": typeof DashboardGoalsCreateRoute;
  "/dashboard/goals": typeof DashboardGoalsIndexRoute;
  "/dashboard/send": typeof DashboardSendIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/create": typeof CreateRoute;
  "/wc": typeof WcRoute;
  "/dashboard/savings": typeof DashboardSavingsRoute;
  "/dashboard/settings": typeof DashboardSettingsRoute;
  "/dashboard/wc": typeof DashboardWcRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/goals/create": typeof DashboardGoalsCreateRoute;
  "/dashboard/goals/": typeof DashboardGoalsIndexRoute;
  "/dashboard/send/": typeof DashboardSendIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/create"
    | "/wc"
    | "/dashboard/savings"
    | "/dashboard/settings"
    | "/dashboard/wc"
    | "/dashboard/"
    | "/dashboard/goals/create"
    | "/dashboard/goals"
    | "/dashboard/send";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create"
    | "/wc"
    | "/dashboard/savings"
    | "/dashboard/settings"
    | "/dashboard/wc"
    | "/dashboard"
    | "/dashboard/goals/create"
    | "/dashboard/goals"
    | "/dashboard/send";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/create"
    | "/wc"
    | "/dashboard/savings"
    | "/dashboard/settings"
    | "/dashboard/wc"
    | "/dashboard/"
    | "/dashboard/goals/create"
    | "/dashboard/goals/"
    | "/dashboard/send/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  CreateRoute: typeof CreateRoute;
  WcRoute: typeof WcRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wc": {
      id: "/wc";
      path: "/wc";
      fullPath: "/wc";
      preLoaderRoute: typeof WcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create": {
      id: "/create";
      path: "/create";
      fullPath: "/create";
      preLoaderRoute: typeof CreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/wc": {
      id: "/dashboard/wc";
      path: "/wc";
      fullPath: "/dashboard/wc";
      preLoaderRoute: typeof DashboardWcRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings": {
      id: "/dashboard/settings";
      path: "/settings";
      fullPath: "/dashboard/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/savings": {
      id: "/dashboard/savings";
      path: "/savings";
      fullPath: "/dashboard/savings";
      preLoaderRoute: typeof DashboardSavingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/send/": {
      id: "/dashboard/send/";
      path: "/send";
      fullPath: "/dashboard/send";
      preLoaderRoute: typeof DashboardSendIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/goals/": {
      id: "/dashboard/goals/";
      path: "/goals";
      fullPath: "/dashboard/goals";
      preLoaderRoute: typeof DashboardGoalsIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/goals/create": {
      id: "/dashboard/goals/create";
      path: "/goals/create";
      fullPath: "/dashboard/goals/create";
      preLoaderRoute: typeof DashboardGoalsCreateRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardSavingsRoute: typeof DashboardSavingsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardWcRoute: typeof DashboardWcRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardGoalsCreateRoute: typeof DashboardGoalsCreateRoute;
  DashboardGoalsIndexRoute: typeof DashboardGoalsIndexRoute;
  DashboardSendIndexRoute: typeof DashboardSendIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardGoalsCreateRoute: DashboardGoalsCreateRoute,
  DashboardGoalsIndexRoute: DashboardGoalsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSavingsRoute: DashboardSavingsRoute,
  DashboardSendIndexRoute: DashboardSendIndexRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWcRoute: DashboardWcRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  CreateRoute: CreateRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  IndexRoute: IndexRoute,
  WcRoute: WcRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
