/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as IndexRouteImport } from "./app/index";
import { Route as WcRouteImport } from "./app/wc";

const WcRoute = WcRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/wc",
  path: "/wc",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/wc": typeof WcRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/wc": typeof WcRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/wc": typeof WcRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/wc";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/wc";
  id: "__root__" | "/" | "/wc";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WcRoute: typeof WcRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wc": {
      id: "/wc";
      path: "/wc";
      fullPath: "/wc";
      preLoaderRoute: typeof WcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WcRoute: WcRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
